version: '3.1'

services:

  db:
    image: postgres:alpine3.14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: auth_service

  mail:
    image: marcopas/docker-mailslurper
    ports:
      - 2500:2500
      - 8080:8080
      - 8085:8085
